language: go

go:
  - 1.13.x

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "Boz19xXCHilkNIwxEoGK2xg21M0CIXYDre8S1EtA2spB7tBxyWRz3BK5O8uNRjshaCmkySHsSUgnvES+AQkjx2kxTh4oqnVTHL5n5IPdcZ+04uLoCwYJJSl5agMhYV7s5sjyoiUnXi8NWrz27g1QEz8uhv+jwvz45Zq+BJYWgNYAEPM1lSwyIjPG5eoBWc1A4u6yOGq3txWUgD5w4NEqCdVjqZx/zDWIkUc9G0GKCzyJNyqEag7jvWLJIi6SAVOFGmx3nt0hKdE8k7x4YiRJPo5iJ5iVs+yxrrJ2zvjpjR/Mo2GgzgS7Cekz1nsEZtBBjAuA8a1k0wtr/aD4PzNZD4vvG866mBzqNit2oeXPlEyKx/TOUIvUi9YLh6htY+1C/P/ofNcm2xlyAjqz9do0OOcz2gtrah8GAOsOcFdd/etDkFmzz8f67+ZZFnvEZ7hBMz3hGwMCkHDLDeoudl6APr6kMDfubI6/EsXx5Zy6Te8TjMkGP8LhM2agdPZQqnnLp1AFWL3XvDRr8mDD58BuW6t35zPXJ/+0C9mNfES/Wvvo3sdTp+XjN8BARXuw7Nqu7WqVGdgRmR04j/3TAu7Xum746isL6dtHr9c7DRViVY2DUQVHJGwTH2/D0ampA/C800h/CcxX5928oWEE//C+6v2gmncGvCqdwaa8B4ekyZ0="

    # AWS_SECRET_ACCESS_KEY
    - secure: "CeBKHJNlwzVNRBHdQfbQ3e4f40id1HfA2Hzn5o8up8Zjls9XCl5t/cGbIJCpJoUuZhkIzZapQAiYp0vXAzlA2AngMYjyDaGq5eMAMdVZwCL/jPMGPZNPmO82L8Tz+X/e2q8rlsOmQR8gqvqU4px1IU58NfiPkoN9Es4R3tTkGIZSI9swxCb/BgJe3d6H7buWqDIQsa2ma2m8HyB0f6x3qk+9o5U5y1iQrrTL8ZqzOaMZSFkNBRcfjBkMG7eH8fzG0sWmAOREFbHId7nRxM3uJ6lwM0XJNE7OLANz64iRlEvwamyWaERyASRysB48nOkC9iPeNUvYSapvkUMihiueoUSnBXnhEFXFQlAUNKR9Iaqx/Pr2kzfkV0532f9NmP8DPd0Be7EpVpd0frX1EEGnH++0gH4VxfnF8OKMXr7OQV75RPVF+mFn4mPhhMzORPuQQksLbNEiyj5xbS4nqo7CWRFxW0jcLqHdmrg6kMPupJQkQlaSz808SY+y0/VL+b0htztCQx7MniiBVo3JcUQF5Y7yqRSNvO4oQzwL856/rPAYv3uAbU5DKGI+g5+cXnVbUkEZRmPiXbPYz/mcvWWGHckRlUgBWfrGrYWxnmJYxODHS7Q9uYKfLnP7WaYd9vdWHFMWlkWKCQcnQIMgLyj4c7MGKo+3vQR8L7H/shcLtns="

    - AWS_REGION="us-east-1"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - INTEGRATION=1 go test -race

after_success:
  - bash <(curl -s https://codecov.io/bash)
